import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('manual production storage cleanup workflow stays gated, resumable and bounded per operation', () => {
  const workflow = readFileSync(new URL('../.github/workflows/production-storage-cleanup.yml', import.meta.url), 'utf8');
  const runner = readFileSync(new URL('../scripts/run-production-storage-cleanup.mjs', import.meta.url), 'utf8');

  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /EXECUTE REVIEWED STORAGE CLEANUP/);
  assert.match(workflow, /STORAGE_CLEANUP_TOKEN/);
  assert.match(workflow, /wrangler@4\.114\.0 secret put STORAGE_CLEANUP_TOKEN/);
  assert.match(workflow, /secret delete STORAGE_CLEANUP_TOKEN/);
  assert.doesNotMatch(workflow, /secrets\.ADMIN_TOKEN|secrets\.KENTAURAI_ADMIN_TOKEN/);
  assert.match(workflow, /time_travel\/bookmark/);
  assert.match(workflow, /Wait for cleanup auth to propagate/);
  assert.match(workflow, /storage-cleanup\/auth-check/);
  assert.match(workflow, /seq 1 15/);
  assert.match(workflow, /concurrency:/);
  assert.doesNotMatch(workflow, /schedule:/);
  assert.match(workflow, /CLEANUP_SOFT_DEADLINE_MS: "2100000"/);
  assert.match(workflow, /CLEANUP_RUN_MAX_ROWS_READ: "1000000"/);
  assert.match(workflow, /CLEANUP_RUN_MAX_ROWS_WRITTEN: "100000"/);
  assert.match(workflow, /Refuse automatic continuation after cumulative cost stop/);
  assert.match(workflow, /cost_budget_stop/);
  assert.match(workflow, /Queue controlled continuation/);
  assert.match(workflow, /actions\/workflows\/production-storage-cleanup\.yml\/dispatches/);
  assert.match(workflow, /actions: write/);
  assert.match(workflow, /Require exact deployed main/);
  assert.match(workflow, /production-release-v060\.yml\/runs\?branch=main&status=success&per_page=1/);
  assert.match(workflow, /deployed_sha.*GITHUB_SHA/s);
  assert.match(workflow, /continuation_session:/);
  assert.match(workflow, /CLEANUP_SESSION_ID:/);
  assert.match(workflow, /cleanup_session_id/);
  assert.match(workflow, /Verify production health after cleanup run[\s\S]*always\(\) && steps\.worker\.outcome == 'success'/);

  assert.match(runner, /DRY_RUN_MAX_BATCHES > 250/);
  assert.match(runner, /while \(MODE === 'execute' \|\| runPages < DRY_RUN_MAX_BATCHES\)/);
  assert.match(runner, /while \(MODE === 'execute' \|\| runBatches < DRY_RUN_MAX_BATCHES\)/);
  assert.match(runner, /storage-cleanup\/audit/);
  assert.match(runner, /storage-cleanup\/session\/audit/);
  assert.match(runner, /storage cleanup integrity audit failed; refusing cleanup|storage cleanup session integrity audit failed; refusing cleanup/);
  assert.match(runner, /storage-cleanup\/session\/start/);
  assert.match(runner, /storage-cleanup\/session\/checkpoint/);
  assert.match(runner, /GITHUB_SHA/);
  assert.match(runner, /continuation limit reached before completion/);
  assert.match(runner, /deadlineReached\(\)/);
  assert.match(runner, /limit: 25/);
  assert.match(runner, /safetyStop === true/);
  assert.match(runner, /execution count differed from its dry-run plan/);
  assert.match(runner, /response\.status === 401/);
  assert.match(runner, /attempt <= 15/);
  assert.doesNotMatch(runner, /storage-cleanup\/state/);
  assert.doesNotMatch(runner, /historical_all|backfill|repair/i);
});

test('GitHub dry-run continuation puts the audit ID first and recovers accidental session entry', () => {
  const workflow = readFileSync(new URL('../.github/workflows/production-storage-cleanup.yml', import.meta.url), 'utf8');
  const runner = readFileSync(new URL('../scripts/run-production-storage-cleanup.mjs', import.meta.url), 'utf8');
  const auditIndex = workflow.indexOf('      continuation_audit:');
  const sessionIndex = workflow.indexOf('      continuation_session:');
  assert.ok(auditIndex > 0 && sessionIndex > auditIndex, 'Audit-ID field must precede execute-only session field');
  assert.match(workflow, /EXECUTE ONLY: internal cleanup session/);
  assert.match(workflow, /Validate cleanup continuation fields before costly work/);
  assert.match(workflow, /Dry-run has two IDs/);
  assert.match(runner, /recoveredMisfiledAuditId = MODE === 'dry-run'/);
  assert.match(runner, /audit_run_id: error\.auditRunId/);
  assert.match(runner, /error\?\.cleanupReason === 'audit_already_running'/);
  assert.match(runner, /safeResetReasons\.has\(error\?\.cleanupReason\)/);
  assert.match(runner, /MODE !== 'dry-run' \|\| !CLEANUP_AUDIT_RUN_ID/);
  assert.doesNotMatch(workflow, /schedule:/);
});
